version: "3"
services:
  timer-fe:
    build:
      context: timer-fe/
      dockerfile: Dockerfile
      args:
        JAR_FILE: "target/timer-fe-0.0.1-SNAPSHOT.jar"
    image: syracus/timer-fe:latest
    ports:
      - "8080:8080"
    links:
      - timer-ws
  timer-ws:
    build:
      context: timer-ws/
      dockerfile: Dockerfile
      args:
        JAR_FILE: "target/timer-ws-0.0.1-SNAPSHOT.jar"
    image: syracus/timer-ws:latest
    ports:
      - "8090:8090"
